spring:
  application:
    name: screening-report-service
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: null
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
server:
  port: 8185
info:
  component: Screening Report Service
eureka:
  client:
    service-url:
      defaultZone: ${SCREENFORCE_EUREKA_SERVER_URL}